In [2]:
! pip3 install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/anuruddhapratapsinghkushwah/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/anuruddhapratapsinghkushwah/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
! pip3 install --upgrade pip

Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (26.2.1)

# PANDAS

**Pandas** is a popular Python library used for **data manipulation and data analysis**. It makes it easy to work with structured data such as tables, CSV files, and Excel files.

## Main Data Structures

* **Series** — A one-dimensional labeled data structure, similar to a single column.
* **DataFrame** — A two-dimensional table with rows and columns, similar to an Excel spreadsheet.

## What Can Pandas Do?

* Read and write CSV and Excel files
* Filter and sort data
* Handle missing values
* Add, remove, and modify columns
* Group and summarize data
* Perform data analysis and statistics

## Example

```python
import pandas as pd

data = {
    "Name": ["Amit", "Rahul", "Priya"],
    "Age": [20, 21, 19]
}

df = pd.DataFrame(data)

print(df)
```

### Output

```text
    Name  Age
0   Amit   20
1  Rahul   21
2  Priya   19
```

> **In short:** Pandas is like a powerful programming version of Excel tables, mainly used for working with and analyzing data in Python.

In [4]:
import pandas as pd
import numpy as np

In [5]:
# pd.DataFrame() - creates a table from dictionary
data = {
    'table_no' : [12,13,14,15,16],
    'bill_amount' : [100,10000,100,0,10],
    'waiter_name' : ['Anugrah', 'Sharief', 'Preetam' , 'Pratham', 'Ayush']
}
df = pd.DataFrame(data)

print(df)
print("Data Type :",type(df))

print(df['table_no'])
print(type(df['table_no']))

   table_no  bill_amount waiter_name
0        12          100     Anugrah
1        13        10000     Sharief
2        14          100     Preetam
3        15            0     Pratham
4        16           10       Ayush
Data Type : <class 'pandas.DataFrame'>
0    12
1    13
2    14
3    15
4    16
Name: table_no, dtype: int64
<class 'pandas.Series'>

In [6]:
# .values / .to_numpy() - the NumPy array underneath
print(df.values)
print(type(df.values))
print()
print(df.to_numpy())
print(type(df.to_numpy()))

[[12 100 'Anugrah']
 [13 10000 'Sharief']
 [14 100 'Preetam']
 [15 0 'Pratham']
 [16 10 'Ayush']]
<class 'numpy.ndarray'>

[[12 100 'Anugrah']
 [13 10000 'Sharief']
 [14 100 'Preetam']
 [15 0 'Pratham']
 [16 10 'Ayush']]
<class 'numpy.ndarray'>

In [7]:
# pd.Series() - 1D data with an index
total_bill = [4700,5678,1253,1000]
s = pd.Series(total_bill, index = ['mon','tue','wed','fri'])
print(s)
print(type(s))

mon    4700
tue    5678
wed    1253
fri    1000
dtype: int64
<class 'pandas.Series'>

In [8]:
# Q1 --
s = [45,30,15,60]
s = pd.Series(s ,index = ['PIZZA','PASTA','FRIES','BURGER'])
print(s)

PIZZA     45
PASTA     30
FRIES     15
BURGER    60
dtype: int64

In [9]:
# Q2 --
p = {
    'Brand' : ['Puma', 'Campus','Nike'],
    'Price' : [2500,6000,7900]
}
df = pd.DataFrame(p)

print(df)

    Brand  Price
0    Puma   2500
1  Campus   6000
2    Nike   7900

In [10]:
# pd.read_csv
df = pd.read_csv("../Data/tip.csv") # returns data frame
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [11]:
# head()
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [12]:
# tail()
df.tail(5)

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [13]:
# random value of in form of a row
df.sample(3) # all 3 rows are random

     total_bill   tip   sex smoker  day    time  size
163       13.81  2.00  Male     No  Sun  Dinner     2
112       38.07  4.00  Male     No  Sun  Dinner     3
180       34.65  3.68  Male    Yes  Sun  Dinner     4

In [14]:
# .shape given no. of rows and columns
print(df.shape)
print(df.columns)

(244, 7)
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [15]:
# info() - dtypes and null counts in one shot
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [16]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [17]:
# .value_counts() , .unique() , .nunique()
print(df['day'].value_counts()) # Count of all the values
print(df['day'].unique()) # all the uniques
print(df['day'].nunique()) # number of uniques

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str
4